import { jsPDF } from 'jspdf'
import { layoutBracket, METRICS } from '../components/bracket/bracketMath'
import { victoryLabel } from './utils'

// Brand palette (print-friendly - white background, gold/black accents,
// not the app's own near-black UI theme, which doesn't translate to a
// printed page). Hex values match web/src/index.css's --color-gold-*/mat-*.
const GOLD = '#c08f1e'
const GOLD_LIGHT = '#e8ae2e'
const INK = '#1d1d22'
const INK_MUTED = '#6b6b74'
const LINE = '#c9c2b0'
const WIN_BG = '#faf3df'
const BYE_BG = '#f4f1ea'

const PAGE_W = 612 // 8.5in @ 72dpi (jsPDF default pt units, letter size)
const PAGE_H = 792
const MARGIN = 40

function addBrandedHeader(doc, title, subtitle, pageW = PAGE_W, margin = MARGIN) {
  doc.setFillColor(GOLD)
  doc.rect(0, 0, pageW, 6, 'F')

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.setTextColor(GOLD)
  doc.text('MAT SAVVY', margin, 26)

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(15)
  doc.setTextColor(INK)
  doc.text(title, margin, 46)

  if (subtitle) {
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    doc.setTextColor(INK_MUTED)
    doc.text(subtitle, margin, 60)
  }

  doc.setDrawColor(GOLD_LIGHT)
  doc.setLineWidth(1)
  doc.line(margin, 68, pageW - margin, 68)

  return 84 // y-offset where page content should start
}

function addFooter(doc, pageLabel, pageW = PAGE_W, margin = MARGIN) {
  const pageH = doc.internal.pageSize.getHeight()
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(8)
  doc.setTextColor(INK_MUTED)
  doc.text('Generated by Mat Savvy', margin, pageH - 16)
  doc.text(new Date().toLocaleDateString(undefined, { year: 'numeric', month: 'long', day: 'numeric' }), pageW - margin, pageH - 16, { align: 'right' })
  if (pageLabel) {
    doc.text(pageLabel, pageW / 2, pageH - 16, { align: 'center' })
  }
}

/**
 * Exports a Pick'em entry as a clean, vector-text PDF table (no screenshot
 * needed - it's inherently list data, so drawing it directly gives crisper,
 * smaller, more "official picks sheet" output than a rasterized capture).
 */
export function exportPickemPDF({ tournamentName, tournamentYear, ownerName, entry, picks }) {
  const doc = new jsPDF({ unit: 'pt', format: 'letter' })
  const subtitle = [tournamentName, tournamentYear].filter(Boolean).join(' · ') + (ownerName ? ` — ${ownerName}'s picks` : '')
  let y = addBrandedHeader(doc, "Pick'em Picks", subtitle)

  // Summary stat line
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  doc.setTextColor(INK)
  const summaryParts = []
  if (entry?.total_points != null) summaryParts.push(`Total points: ${entry.total_points}`)
  if (entry?.rank != null) summaryParts.push(`Rank: #${entry.rank}`)
  if (entry?.points_used != null) summaryParts.push(`Budget used: ${entry.points_used}`)
  doc.text(summaryParts.join('   ·   '), MARGIN, y)
  y += 24

  // Table header
  const colX = { weight: MARGIN, wrestler: MARGIN + 60, cost: PAGE_W - MARGIN - 110, points: PAGE_W - MARGIN - 40 }
  doc.setFillColor('#f2ede1')
  doc.rect(MARGIN, y - 12, PAGE_W - MARGIN * 2, 20, 'F')
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(9)
  doc.setTextColor(INK_MUTED)
  doc.text('WEIGHT', colX.weight + 4, y + 2)
  doc.text('WRESTLER', colX.wrestler + 4, y + 2)
  doc.text('COST', colX.cost, y + 2, { align: 'right' })
  doc.text('POINTS', colX.points, y + 2, { align: 'right' })
  y += 22

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)

  const rowH = 22
  let pageNum = 1
  const pageCount = Math.max(1, Math.ceil(picks.length / 30))

  for (const p of picks) {
    if (y > PAGE_H - 80) {
      addFooter(doc, pageCount > 1 ? `Page ${pageNum} of ${pageCount}` : undefined)
      doc.addPage()
      pageNum += 1
      y = addBrandedHeader(doc, "Pick'em Picks", subtitle) + 10
    }

    doc.setDrawColor('#e6e0d2')
    doc.setLineWidth(0.5)
    doc.line(MARGIN, y + 6, PAGE_W - MARGIN, y + 6)

    const weightLabel = p.weight_class?.weight != null ? `${p.weight_class.weight}` : p.weight_class?.name ?? '—'
    doc.setTextColor(GOLD)
    doc.setFont('helvetica', 'bold')
    doc.text(String(weightLabel), colX.weight + 4, y)

    doc.setTextColor(INK)
    doc.setFont('helvetica', 'normal')
    const seed = p.wrestler?.seed != null ? `(${p.wrestler.seed}) ` : ''
    const school = p.wrestler?.school ? `  —  ${p.wrestler.school}` : ''
    const wrestlerLine = p.wrestler ? `${seed}${p.wrestler.name}${school}` : '—'
    doc.text(wrestlerLine, colX.wrestler + 4, y, { maxWidth: colX.cost - colX.wrestler - 20 })

    doc.text(p.cost != null ? String(p.cost) : '—', colX.cost, y, { align: 'right' })
    doc.setFont('helvetica', 'bold')
    doc.text(p.points_earned != null ? String(p.points_earned) : '—', colX.points, y, { align: 'right' })

    y += rowH
  }

  addFooter(doc, pageCount > 1 ? `Page ${pageNum} of ${pageCount}` : undefined)

  const filename = `mat-savvy-pickem-${(tournamentName || 'entry').toLowerCase().replace(/[^a-z0-9]+/g, '-')}.pdf`
  doc.save(filename)
}

// Championship brackets are tall-ish and narrow (few columns, many round-1
// rows) so portrait actually gives them a bigger scale than landscape would;
// consolation brackets are wide (extra pigtail/R-cycle columns plus the
// placement column) and genuinely need landscape's width to stay legible.
const BMARGIN = 26

function pageDims(orientation) {
  return orientation === 'portrait' ? { w: 612, h: 792 } : { w: 792, h: 612 }
}

function drawConnector(doc, srcPos, dstPos, slot, originX, originY, scale) {
  const { MATCH_W, MATCH_H } = METRICS
  const sx = originX + (srcPos.x + MATCH_W) * scale
  const sy = originY + (srcPos.y + MATCH_H / 2) * scale
  const dx = originX + dstPos.x * scale
  const dy = originY + (dstPos.y + (slot === 'bottom' ? MATCH_H * 0.74 : MATCH_H * 0.26)) * scale
  const midX = sx + (dx - sx) * 0.5
  doc.setDrawColor(LINE)
  doc.setLineWidth(0.75)
  doc.line(sx, sy, midX, sy)
  doc.line(midX, sy, midX, dy)
  doc.line(midX, dy, dx, dy)
}

function truncateToWidth(doc, text, maxWidth) {
  if (!text) return ''
  if (doc.getTextWidth(text) <= maxWidth) return text
  let out = text
  while (out.length > 1 && doc.getTextWidth(out + '…') > maxWidth) out = out.slice(0, -1)
  return out + '…'
}

/** One competitor row (top or bottom half) inside a match box, in print form. */
function drawSlot(doc, match, slot, comp, x, y, w, h, scale) {
  const officialWinner = match.winner_competitor_id
  const isWinner = !!officialWinner && comp?.id === officialWinner
  const isLoser = !!officialWinner && comp?.id != null && comp?.id !== officialWinner
  const userPick = match.user_pick
  const hasRealResult = match.status === 'complete' || match.status === 'corrected'
  const showOutcome = hasRealResult && userPick && comp && userPick.wrestler_id === comp.id

  if (isWinner) {
    doc.setFillColor(WIN_BG)
    doc.rect(x, y, w, h, 'F')
  }

  const seedSize = 15 * scale
  const padX = 5 * scale
  const seedX = x + padX
  const seedY = y + h / 2

  doc.setDrawColor(LINE)
  doc.setLineWidth(0.5)
  doc.rect(seedX, seedY - seedSize / 2, seedSize, seedSize)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(Math.max(5, 7 * scale))
  doc.setTextColor(comp ? GOLD : INK_MUTED)
  doc.text(comp?.seed != null ? String(comp.seed) : '–', seedX + seedSize / 2, seedY + 2.5 * scale, { align: 'center' })

  const textX = seedX + seedSize + padX
  const rightPad = 34 * scale
  const textMaxW = x + w - rightPad - textX

  // Below a certain slot height, two stacked lines (name + school/record)
  // no longer both fit without overlapping - collapse to one combined line
  // instead of letting the text spill into the row below (an early NCAA
  // round can be 16+ matches tall, forcing a small scale for the whole page).
  const twoLine = h >= 20

  if (comp) {
    const sub = [comp.school, comp.record].filter(Boolean).join(' · ')
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(twoLine ? Math.max(6, 8.5 * scale) : Math.max(5.5, 7.5 * scale))
    doc.setTextColor(isLoser ? '#9a9488' : INK)
    const nameY = twoLine ? y + h / 2 - 3 * scale : y + h / 2 + 2.5 * scale
    const nameStr = truncateToWidth(doc, twoLine ? (comp.name ?? '') : `${comp.name ?? ''}${sub ? ` (${sub})` : ''}`, textMaxW)
    doc.text(nameStr, textX, nameY)
    if (isLoser) {
      const w2 = doc.getTextWidth(nameStr)
      doc.setDrawColor('#b23b3b')
      doc.setLineWidth(0.6)
      doc.line(textX, nameY - 2.5 * scale, textX + w2, nameY - 2.5 * scale)
    }

    if (twoLine && sub) {
      doc.setFont('helvetica', 'normal')
      doc.setFontSize(Math.max(5, 6.5 * scale))
      doc.setTextColor(INK_MUTED)
      doc.text(truncateToWidth(doc, sub, textMaxW), textX, y + h / 2 + 7 * scale)
    }
  } else {
    doc.setFont('helvetica', 'italic')
    doc.setFontSize(Math.max(5, 7 * scale))
    doc.setTextColor(INK_MUTED)
    doc.text(match[`${slot}_fallback`] || 'TBD', textX, y + h / 2 + 2.5 * scale)
  }

  // right-side outcome marker
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(Math.max(5, 7 * scale))
  if (isWinner) {
    doc.setTextColor('#2f7d4f')
    doc.text('W', x + w - 12 * scale, y + h / 2 + 2.5 * scale, { align: 'center' })
  } else if (showOutcome && userPick.outcome === 'correct') {
    doc.setTextColor('#2f7d4f')
    doc.text(`+${userPick.points_earned ?? ''}`, x + w - padX, y + h / 2 + 2.5 * scale, { align: 'right' })
  } else if (showOutcome && userPick.outcome === 'incorrect') {
    doc.setTextColor('#b23b3b')
    doc.text('X', x + w - 12 * scale, y + h / 2 + 2.5 * scale, { align: 'center' })
  }
}

function drawMatchBox(doc, match, pos, originX, originY, scale) {
  const { MATCH_W, MATCH_H } = METRICS
  const x = originX + pos.x * scale
  const y = originY + pos.y * scale
  const w = MATCH_W * scale
  const h = MATCH_H * scale
  const isFinal = match.round_code === 'champ_finals'

  if (match.is_bye) {
    doc.setFillColor(BYE_BG)
    doc.rect(x, y, w, h, 'F')
  }
  doc.setDrawColor(isFinal ? GOLD : LINE)
  doc.setLineWidth(isFinal ? 1.25 : 0.75)
  doc.rect(x, y, w, h)

  // Meta strip (match number / FINAL + result) lives INSIDE the box's own
  // top edge, not floating above it - floating above only has the row gap
  // to work with, and an early NCAA round can pack 16 boxes tight enough
  // that the gap is smaller than the text, overlapping the row above.
  const metaFont = Math.max(5, 6 * scale)
  const metaH = Math.min(h * 0.24, metaFont + 5)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(metaFont)
  doc.setTextColor(isFinal ? GOLD : INK_MUTED)
  const leftLabel = isFinal ? 'FINAL' : `#${match.match_number}`
  doc.text(leftLabel, x + 4 * scale, y + metaH - 3)
  if ((match.status === 'complete' || match.status === 'corrected') && (match.victory_type || match.score)) {
    const rightLabel = `${victoryLabel(match.victory_type)}${match.score ? ` ${match.score}` : ''}`
    // Only draw the result if it actually fits next to the match number -
    // at extreme compression (early rounds) a narrow box has room for one
    // or the other, not both, and a dropped result beats overlapping text.
    const gap = 6 * scale
    if (doc.getTextWidth(leftLabel) + doc.getTextWidth(rightLabel) + gap < w - 8 * scale) {
      doc.setTextColor(INK_MUTED)
      doc.text(rightLabel, x + w - 4 * scale, y + metaH - 3, { align: 'right' })
    }
  }

  const slotH = (h - metaH) / 2
  drawSlot(doc, match, 'top', match.top?.competitor, x, y + metaH, w, slotH, scale)
  doc.setDrawColor(LINE)
  doc.setLineWidth(0.4)
  doc.line(x + 4 * scale, y + metaH + slotH, x + w - 4 * scale, y + metaH + slotH)
  drawSlot(doc, match, 'bottom', match.bottom?.competitor, x, y + metaH + slotH, w, slotH, scale)

  if (match.is_bye) {
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(Math.max(5, 6 * scale))
    doc.setTextColor(INK_MUTED)
    doc.text('BYE', x + w - 6 * scale, y + metaH + slotH + 2, { align: 'right' })
  }
}

/**
 * Renders one bracket section (championship, or consolation+placement) for
 * one weight class as its own page(s) of pure vector drawing - boxes, lines
 * and text laid out with the app's own layoutBracket() math, not a
 * screenshot of the on-screen dark UI. Keeps the PDF small, sharp at any
 * zoom, and printer-friendly (white page, ink-light).
 *
 * orientation ('portrait' | 'landscape') should match the section's actual
 * shape: championship brackets are narrow-and-tall (few columns, many
 * round-1 rows) so portrait fits them at a bigger scale, while consolation
 * brackets are wide (extra R-cycle/placement columns) and need landscape.
 *
 * isFirstPage must be true only for the very first call against a fresh
 * jsPDF doc (which already starts with one blank page matching that first
 * call's own orientation) - every later section/weight adds its own page.
 */
export function drawBracketSectionPage(doc, matches, { sectionLabel, weightLabel, tournamentName, tournamentYear, ownerName, isFirstPage, orientation = 'landscape' }) {
  const { w: pageW, h: pageH } = pageDims(orientation)
  if (!isFirstPage) doc.addPage('letter', orientation)
  const subtitle = [tournamentName, tournamentYear].filter(Boolean).join(' · ') + (ownerName ? ` — ${ownerName}'s bracket` : '')
  const y0 = addBrandedHeader(doc, `${weightLabel} — ${sectionLabel}`, subtitle, pageW, BMARGIN)

  if (!matches.length) {
    doc.setFont('helvetica', 'italic')
    doc.setFontSize(10)
    doc.setTextColor(INK_MUTED)
    doc.text('No matches in this bracket section.', BMARGIN, y0 + 20)
    addFooter(doc, undefined, pageW, BMARGIN)
    return
  }

  const layout = layoutBracket(matches)
  const headerRowH = 16
  const availW = pageW - BMARGIN * 2
  const availH = pageH - y0 - 24 - headerRowH
  const scale = Math.min(availW / layout.width, availH / layout.height, 1.15)
  const originX = BMARGIN + Math.max(0, (availW - layout.width * scale) / 2)
  const originY = y0 + headerRowH + Math.max(0, (availH - layout.height * scale) / 2)

  // Column headers: one shared label per (band, col) for championship/
  // consolation rounds (every match in that column shares a round), but
  // per-match for the placement column (it stacks 3rd/5th/7th place bouts,
  // each its own distinct round, into a single layout column).
  const seenCols = new Set()
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(7)
  doc.setTextColor(GOLD)
  for (const m of matches) {
    const p = layout.pos.get(m.id)
    if (!p) continue
    const label = m.round_code === 'champ_finals' ? 'FINAL' : (m.round_label || `Round ${m.round_number ?? ''}`)
    if (p.band === 'placement') {
      doc.text(label.toUpperCase(), originX + (p.x + METRICS.MATCH_W / 2) * scale, originY + p.y * scale - 5, { align: 'center' })
      continue
    }
    const colKey = `${p.band}:${p.col}`
    if (seenCols.has(colKey)) continue
    seenCols.add(colKey)
    doc.text(label.toUpperCase(), originX + (p.x + METRICS.MATCH_W / 2) * scale, originY - 5, { align: 'center' })
  }

  for (const m of matches) {
    const p = layout.pos.get(m.id)
    if (!p) continue
    for (const slot of ['top', 'bottom']) {
      const srcId = m[slot]?.source?.match_id
      if (srcId && layout.pos.get(srcId)) {
        drawConnector(doc, layout.pos.get(srcId), p, slot, originX, originY, scale)
      }
    }
  }
  for (const m of matches) {
    const p = layout.pos.get(m.id)
    if (p) drawMatchBox(doc, m, p, originX, originY, scale)
  }

  addFooter(doc, undefined, pageW, BMARGIN)
}

export function createBracketPdfDoc(firstPageOrientation = 'landscape') {
  return new jsPDF({ unit: 'pt', format: 'letter', orientation: firstPageOrientation })
}

export function saveBracketPdf(doc, tournamentName) {
  const filename = `mat-savvy-bracket-${(tournamentName || 'entry').toLowerCase().replace(/[^a-z0-9]+/g, '-')}.pdf`
  doc.save(filename)
}
